[book]
authors = ["Brett Chalupa", "Jorge Dominguez", "Dragon Rider Community"]
language = "en"
multilingual = false
src = "src"
title = "Building Games with DragonRuby (Spanish Edition)"
description = "A free book about making 2D games with DragonRuby Game Toolkit."

[output.html]
git-repository-url = "https://github.com/DragonRidersUnite/book"

[output.html.print]
enable = false
